# Generated by Django 2.2.16 on 2020-09-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
